import streamlit as st
import pickle
import numpy as np
import os
import pytz
from llm_utils import generate_health_advice
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import A4
from io import BytesIO
from datetime import datetime

st.set_page_config(page_title="HealthPredict AI (Heart Disease Risk Prediction)",page_icon="🏩", layout="centered")

# Load ML model (cached)
@st.cache_resource
def load_ml_model():
    return pickle.load(open("models/heart_model.pkl", "rb"))

try:
    model = load_ml_model()
except:
    st.error("Model not found. Please train the model first.")
    st.stop()


st.sidebar.markdown(
    """
    <div style="background-color: black; padding: 5px; border-radius: 10px;">
        <h2 style="color: white; text-align: center;">🧠<b> HealthPredict AI</b></h2>
    </div>
    """,
    unsafe_allow_html=True
)

# PDF Generator
def generate_pdf(advice_text, name, age, gender, trestbps, chol, thalach, risk_text):
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=30,
        leftMargin=30,
        topMargin=30,
        bottomMargin=30
    )
    elements = []

    styles = getSampleStyleSheet()
    style_normal = styles["Normal"]

    logo_path = os.path.join("assets", "healthpredict_logo.png")

    if os.path.exists(logo_path):
        img = Image(logo_path, width=2*inch, height=1*inch)
        img.hAlign = 'CENTER'
        elements.append(img)
        elements.append(Spacer(1, 0.2 * inch))

    elements.append(Paragraph("<b><u>AI-Based Heart Disease Risk Report</u></b>", styles["Heading1"]))

    elements.append(Spacer(1, 0.2 * inch))
    elements.append(Paragraph(
        f"<b>Date:</b> {datetime.now(pytz.timezone('Asia/Kolkata')).strftime('%d-%m-%Y %H:%M')}",style_normal))

    display_name = name if name.strip() != "" else "Not Provided"
    elements.append(Paragraph(f"<b>Patient Name:</b> {display_name}", style_normal))

    elements.append(Spacer(1, 0.2 * inch))
    elements.append(Paragraph("<b>Patient Details:</b>", styles["Heading2"]))

    elements.append(Spacer(1, 0.2 * inch))
    elements.append(Paragraph(f"Age: {age}", style_normal))
    elements.append(Paragraph(f"Gender: {gender}", style_normal))
    elements.append(Paragraph(f"Resting Blood Pressure: {trestbps} mm Hg", style_normal))
    elements.append(Paragraph(f"Cholesterol: {chol} mg/dl", style_normal))
    elements.append(Paragraph(f"Maximum Heart Rate: {thalach}", style_normal))

    elements.append(Spacer(1, 0.2 * inch))
    elements.append(Paragraph(f"<b>Prediction Result:</b> {risk_text}", style_normal))

    elements.append(Spacer(1, 0.2 * inch))
    elements.append(Paragraph("<b>AI Health Advice:</b>", styles["Heading2"]))

    elements.append(Spacer(1, 0.2 * inch))
    elements.append(Paragraph(advice_text.replace("\n", "<br/>"), style_normal))

    elements.append(Spacer(1, 0.4 * inch))
    elements.append(Paragraph(
        "<i>Disclaimer: This report is generated by an AI system for educational purposes only. "
        "It is not a substitute for professional medical advice.</i>",
        style_normal
    ))

    doc.build(elements)
    buffer.seek(0)
    return buffer

# Main Page

st.header("❤️ Heart Disease Risk Prediction")
name = st.text_input("Patient Name")
col1, col2 = st.columns(2)

with col1:
    age = st.number_input("Age", 18, 120)
    trestbps = st.number_input("Resting Blood Pressure (mm Hg)", 80, 200)
    chol = st.number_input("Cholesterol (mg/dl)", 100, 400)

with col2:
    gender = st.selectbox("Gender", ["Male", "Female"])
    if gender == "Male":
        gender_encoded = 1
    else:
        gender_encoded = 0
    thalach = st.number_input("Maximum Heart Rate", 60, 220)

if st.button("Predict Heart Risk"):

    data = np.array([[age, gender_encoded, trestbps, chol, thalach]])
    prediction = model.predict(data)[0]
    probability = model.predict_proba(data)[0][1] * 100

    if prediction == 0:
        risk_text = f"Low Risk ({probability:.2f}%)"
        st.success(f"🟢 {risk_text}")
    else:
        risk_text = f"Heart Disease Risk Detected ({probability:.2f}%)"
        st.error(f"🔴 {risk_text}")

    st.progress(int(probability))
    st.caption("⚠️ This probability is based on statistical ML prediction, not clinical diagnosis.")

    prompt = f"""
    Patient {name}, Age {age}, BP {trestbps}, Cholesterol {chol}, HR {thalach}, Gender {gender_encoded}.
    Risk: {risk_text}.

        Provide:
        - Recommended diet
        - Foods to avoid
        - Exercise plan
        - Heart health tips

        Keep it short and practical.

        Please follow these rules strictly:
        - Complete all sections fully.
        - Do NOT stop mid-sentence.
        - End the response with the word: END
    """

    with st.spinner("Generating AI advice..."):
        advice = generate_health_advice(prompt)

    st.subheader("💞 AI Health Advice")
    st.write(advice)

    pdf_buffer = generate_pdf(advice, name, age, gender, trestbps, chol, thalach, risk_text)

    st.download_button(
        label="📜 Download PDF Report",
        data=pdf_buffer,
        file_name="heart_health_report.pdf",
        mime="application/pdf"
    )
