import streamlit as st
import pickle
import numpy as np
import os
import pytz
import uuid
from llm_utils import generate_health_advice
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import A4
from io import BytesIO
from datetime import datetime

st.set_page_config(page_title="HealthPredict AI (Heart Disease Risk Prediction)",page_icon="🏩", layout="centered")

# Load ML model (cached)
@st.cache_resource
def load_ml_model():
    return pickle.load(open("models/heart_model.pkl", "rb"))

try:
    model = load_ml_model()
except:
    st.error("Model not found. Please train the model first.")
    st.stop()


st.sidebar.markdown(
    """
    <div style="background-color: black; padding: 5px; border-radius: 10px;">
        <h2 style="color: white; text-align: center;">🧠<b> HealthPredict AI</b></h2>
    </div>
    """,
    unsafe_allow_html=True
)

# PDF Generator
def generate_pdf(advice_text, name, age, gender, smoker, diabetes, totChol, sysBP, diaBP, height, weight, bmi, glucose, risk_text):

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=30,
        leftMargin=30,
        topMargin=30,
        bottomMargin=30
    )
    elements = []

    styles = getSampleStyleSheet()
    style_normal = styles["Normal"]

    logo_path = os.path.join("assets", "healthpredict_logo.png")
    if os.path.exists(logo_path):
        img = Image(logo_path, width=2*inch, height=1*inch)
        img.hAlign = 'CENTER'
        elements.append(img)
        elements.append(Spacer(1, 0.2 * inch))

    elements.append(Paragraph("<b><u>AI-Based Heart Disease Risk Report</u></b>", styles["Heading1"]))
    report_id = str(uuid.uuid4())[:8]

    elements.append(Spacer(1, 0.2 * inch))
    elements.append(Paragraph(f"<b>Report ID:</b> HP-{report_id}", style_normal))

    elements.append(Spacer(1, 0.2 * inch))
    elements.append(Paragraph(
        f"<b>Date:</b> {datetime.now(pytz.timezone('Asia/Kolkata')).strftime('%d-%m-%Y %H:%M')}",style_normal))

    display_name = name if name.strip() != "" else "Not Provided"
    elements.append(Paragraph(f"<b>Patient Name:</b> {display_name}", style_normal))

    elements.append(Spacer(1, 0.2 * inch))
    elements.append(Paragraph("<b>Patient Details:</b>", styles["Heading2"]))

    elements.append(Spacer(1, 0.2 * inch))
    elements.append(Paragraph(f"Age: {age}", style_normal))
    elements.append(Paragraph(f"Gender: {gender}", style_normal))
    elements.append(Paragraph(f"Height: {height} cm", style_normal))
    elements.append(Paragraph(f"Weight: {weight} kg", style_normal))
    elements.append(Paragraph(f"Calculated BMI: {bmi:.2f}", style_normal))
    elements.append(Paragraph(f"Smoker: {smoker}", style_normal))
    elements.append(Paragraph(f"Diabetes: {diabetes}", style_normal))
    elements.append(Paragraph(f"Total Cholesterol: {totChol}", style_normal))
    elements.append(Paragraph(f"Systolic BP: {sysBP}", style_normal))
    elements.append(Paragraph(f"Diastolic BP: {diaBP}", style_normal))
    elements.append(Paragraph(f"Glucose: {glucose}", style_normal))

    elements.append(Spacer(1, 0.2 * inch))
    elements.append(Paragraph(f"<b>Prediction Result:</b> {risk_text}", style_normal))

    elements.append(Spacer(1, 0.2 * inch))
    elements.append(Paragraph("<b>AI Health Advice:</b>", styles["Heading2"]))

    elements.append(Spacer(1, 0.2 * inch))
    elements.append(Paragraph(advice_text.replace("\n", "<br/>"), style_normal))

    elements.append(Spacer(1, 0.4 * inch))
    elements.append(Paragraph(
        "<i>Disclaimer: This report is generated by an AI system for educational purposes only. "
        "It is not a substitute for professional medical advice.</i>",
        style_normal
    ))

    doc.build(elements)
    buffer.seek(0)
    return buffer

# Main Page
st.header("❤️ Heart Disease Risk Prediction")
name = st.text_input("Patient Name")
col1, col2 = st.columns(2)

with col1:
    age = st.number_input("Age", 18, 100)
    height = st.number_input("Height (cm)", 120.0, 220.0)
    sysBP = st.number_input("Systolic BP (mmHg)", 80, 200)
    glucose = st.number_input("Glucose Level", 50, 300)
    diabetes = st.selectbox("Diabetes?", ["No", "Yes"])
    diabetes_encoded = 1 if diabetes == "Yes" else 0

with col2:
    gender = st.selectbox("Gender", ["Male", "Female"])
    male = 1 if gender == "Male" else 0
    weight = st.number_input("Weight (kg)", 30.0, 200.0)
    diaBP = st.number_input("Diastolic BP (mmHg)", 50, 130)
    totChol = st.number_input("Total Cholesterol (mg/dL)", 100, 400)
    smoker = st.selectbox("Current Smoker?", ["No", "Yes"])
    currentSmoker = 1 if smoker == "Yes" else 0


if st.button("Predict Heart Risk"):

    if height <= 0:
        st.error("Height must be greater than zero.")
        st.stop()

    bmi = weight / ((height / 100) ** 2)
    st.info(f"Calculated BMI: {bmi:.2f}")

    data = np.array([[male,age,currentSmoker,diabetes_encoded,totChol,sysBP,diaBP,bmi,glucose]])

    if hasattr(model, "predict_proba"):
        probability = model.predict_proba(data)[0][1] * 100
    else:
        probability = float(model.predict(data)[0]) * 100

    risk_text = f"{probability:.2f}% probability of heart disease"

    if probability < 33:
        st.success(f"🟢 Low Risk Zone ({probability:.2f}%)")
    elif probability < 66:
        st.warning(f"🟡 Moderate Risk Zone ({probability:.2f}%)")
    else:
        st.error(f"🔴 High Risk Zone ({probability:.2f}%)")

    st.progress(int(probability))
    st.subheader("🔎 Key Risk Indicators")

    risk_factors = []

    if sysBP > 140:
        risk_factors.append("High systolic blood pressure")

    if diaBP > 90:
        risk_factors.append("High diastolic blood pressure")

    if totChol > 240:
        risk_factors.append("High cholesterol")

    if bmi > 30:
        risk_factors.append("Obesity (High BMI)")

    if glucose > 125:
        risk_factors.append("High glucose level")

    if currentSmoker == 1:
        risk_factors.append("Current smoker")

    if diabetes_encoded == 1:
        risk_factors.append("Diabetes condition")

    if risk_factors:
        for factor in risk_factors:
            st.write(f"⚠ {factor}")
    else:
        st.write("No major clinical red flags detected.")

    st.caption(
    "⚠️ This probability is derived from Logistic Regression model output. "
    "Values closer to 0% or 100% indicate stronger model confidence. "
    "This is not a medical diagnosis."
    )

    prompt = f"""
    Patient {name}, Age {age},Gender {gender}, Smoker: {smoker}, Diabetes: {diabetes},
    Total Cholesterol: {totChol},Systolic BP: {sysBP}, Diastolic BP: {diaBP},BMI: {bmi:.2f},
    Glucose: {glucose}. 10-year CHD Risk: {risk_text}.

        Provide:
        - Recommended diet
        - Foods to avoid
        - Exercise plan
        - Lifestyle improvements
        - Cardiovascular risk reduction tips

        Keep it short and practical.

        Please follow these rules strictly:
        - Complete all sections fully.
        - Do NOT stop mid-sentence.
        - End the response with the word: END
    """

    with st.spinner("Generating AI advice..."):
        advice = generate_health_advice(prompt)

    st.subheader("💞 AI Health Advice")
    st.write(advice)

    pdf_buffer = generate_pdf(advice, name, age, gender, smoker, diabetes, totChol, sysBP, diaBP, height, weight, bmi, glucose, risk_text)

    st.download_button(
        label="📜 Download PDF Report",
        data=pdf_buffer,
        file_name="heart_health_report.pdf",
        mime="application/pdf"
    )
