import streamlit as st
import pickle
import numpy as np
import os
from llm_utils import generate_health_advice
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import A4
from io import BytesIO
from datetime import datetime

st.set_page_config(page_title="HealthPredict AI (Diabetes Risk Prediction)",page_icon="🏩", layout="centered")

# Load ML model (cached)
@st.cache_resource
def load_ml_model():
    return pickle.load(open("models/diabetes_model.pkl", "rb"))

try:
    model = load_ml_model()
except:
    st.error("Model not found. Please train the model first.")
    st.stop()


st.sidebar.markdown(
    """
    <div style="background-color: black; padding: 5px; border-radius: 10px;">
        <h2 style="color: white; text-align: center;">🧠<b> HealthPredict AI</b></h2>
    </div>
    """,
    unsafe_allow_html=True
)

# PDF Generator (Diabetes)
def generate_pdf(advice_text, name, age, glucose, height, weight, bmi, insulin, gender, risk_text):

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=30,
        leftMargin=30,
        topMargin=30,
        bottomMargin=30
    )

    elements = []
    styles = getSampleStyleSheet()
    style_normal = styles["Normal"]

    # Logo (optional)
    base_dir = os.path.dirname(os.path.abspath(__file__))
    logo_path = os.path.join(base_dir, "assets", "healthpredict_logo.png")

    if os.path.exists(logo_path):
        img = Image(logo_path, width=2*inch, height=1*inch)
        img.hAlign = 'CENTER'
        elements.append(img)
        elements.append(Spacer(1, 0.3 * inch))

    elements.append(Paragraph("<b><u>AI-Based Diabetes Risk Report</u></b>", styles["Heading1"]))
    elements.append(Spacer(1, 0.3 * inch))

    elements.append(Paragraph(f"<b>Date:</b> {datetime.now().strftime('%d-%m-%Y %H:%M')}", style_normal))

    display_name = name if name.strip() != "" else "Not Provided"
    elements.append(Paragraph(f"<b>Patient Name:</b> {display_name}", style_normal))

    elements.append(Spacer(1, 0.3 * inch))
    elements.append(Paragraph("<b>Patient Details:</b>", styles["Heading2"]))
    elements.append(Spacer(1, 0.2 * inch))

    elements.append(Paragraph(f"Age: {age}", style_normal))
    elements.append(Paragraph(f"Gender: {gender}", style_normal))
    elements.append(Paragraph(f"Glucose Level: {glucose}", style_normal))
    elements.append(Paragraph(f"Height: {height} cm", style_normal))
    elements.append(Paragraph(f"Weight: {weight} kg", style_normal))
    elements.append(Paragraph(f"Calculated BMI: {bmi:.2f}", style_normal))

    elements.append(Paragraph(f"Insulin Level: {insulin}", style_normal))

    elements.append(Spacer(1, 0.3 * inch))
    elements.append(Paragraph(f"<b>Prediction Result:</b> {risk_text}", style_normal))

    elements.append(Spacer(1, 0.3 * inch))
    elements.append(Paragraph("<b>AI Health Advice:</b>", styles["Heading2"]))
    elements.append(Spacer(1, 0.2 * inch))
    elements.append(Paragraph(advice_text.replace("\n", "<br/>"), style_normal))

    elements.append(Spacer(1, 0.5 * inch))
    elements.append(Paragraph(
        "<i>Disclaimer: This report is generated by an AI system for educational purposes only. "
        "It is not a substitute for professional medical advice.</i>",
        style_normal
    ))

    doc.build(elements)
    buffer.seek(0)
    return buffer

# Main Page
st.header("🧁 Diabetes Risk Prediction")
name = st.text_input("Patient Name")

col1, col2 = st.columns(2)

with col1:
    age = st.number_input("Age", 18, 120)
    glucose = st.number_input("Glucose Level", 50, 300)
    insulin = st.number_input("Insulin Level (Optional)", 0, 500,value=80)
    st.caption("If unknown, keep default value (80).")

with col2:
    gender = st.selectbox("Gender", ["Male", "Female"])
    if gender == "Male":
        gender_encoded = 1
    else:
        gender_encoded = 0
    height = st.number_input("Height (in cm)", 100.0, 250.0)
    if height <= 0:
        st.error("Height must be greater than zero.")
        st.stop()
    weight = st.number_input("Weight (in kg)", 30.0, 200.0)

if st.button("Predict Diabetes Risk"):

    bmi = weight / ((height / 100) ** 2)
    st.info(f"Calculated BMI: {bmi:.2f}")

    data = np.array([[glucose, bmi, insulin, age, gender_encoded]])
    prediction = model.predict(data)[0]
    probability = model.predict_proba(data)[0][1] * 100

    # 🔥 Risk Level Logic (Same as Heart Page)
    if prediction == 0:
        risk_text = f"Low Risk ({probability:.2f}%)"
        st.success(f"🟢 {risk_text}")
    else:
        risk_text = f"Diabetes Risk Detected ({probability:.2f}%)"
        st.error(f"🔴 {risk_text}")

    st.progress(int(probability))
    st.caption("⚠️ This probability is based on statistical ML prediction, not clinical diagnosis.")

    prompt = f"""
        Patient {name}, Age {age}, Glucose {glucose}, Height {height} cm, Weight {weight} kg, BMI {bmi:.2f}, Insulin {insulin}, Gender {gender_encoded}. 
        Risk: {risk_text}. 

        Provide:
        - Recommended diet plan
        - Foods to avoid
        - Exercise recommendations
        - Blood sugar management tips

        Keep it short and practical.

        Please follow these rules strictly:
        - Complete all sections fully.
        - Do NOT stop mid-sentence.
        - End the response with the word: END
        """

    with st.spinner("Generating AI advice..."):
        advice = generate_health_advice(prompt)

    st.subheader("👼 AI Health Advice")
    st.write(advice)

    pdf_buffer = generate_pdf(advice, name, age, glucose, height, weight, bmi, insulin, gender, risk_text)

    st.download_button(
        label="📜 Download PDF Report",
        data=pdf_buffer,
        file_name="diabetes_health_report.pdf",
        mime="application/pdf"
    )
